# Labolatorium 3 - NumPy
**Autor: Martyna**

In [2]:
import numpy as np

## Ćwiczenie 1

In [3]:
# 1. tablica z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f'Oceny: {oceny}')
print(f'Typ: {oceny.dtype}')

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [4]:
# 2. Tablica zer
zera = np.zeros(10)
print(f'zera: {zera}')

zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# 3. Tablica jedynek - macierz 3x5
jedynki = np.ones((3,5))
print(f'jedynki: {jedynki}')

jedynki: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 4. Tablica - sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f'dziesiątki: {dziesiatki}')

dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [7]:
# 5. Tablica - 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f'ułamki: {ulamki}')

ułamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [8]:
# 6. Tablica 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f'Losowe oceny: {losowe_oceny}')

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [11]:
# Badanie tablicy losowych ocen
print(f'Shape: {losowe_oceny.shape}')
print(f'ndim: {losowe_oceny.ndim}')
print(f'Size: {losowe_oceny.size}')
print(f'dtype: {losowe_oceny.dtype}')

Shape: (20,)
ndim: 1
Size: 20
dtype: int32


## Ćwiczenie 2 
*Część A* - tablica 1D

In [12]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])


In [13]:
print(f'sprzedaż w styczniu: {miesiace_sprzedaz[0]}')

sprzedaż w styczniu: 120


In [14]:
print(f'sprzedaż w grudniu: {miesiace_sprzedaz[-1]}')

sprzedaż w grudniu: 221


In [16]:
print(f'sprzedaz w q1: {miesiace_sprzedaz[0:3]}')
print(f'sprzedaz w q4: {miesiace_sprzedaz[-3:]}')

sprzedaz w q1: [120 135  98]
sprzedaz w q4: [143 198 221]


In [17]:
print(f'sprzedaz co drugi miesiac: {miesiace_sprzedaz[::2]}')

sprzedaz co drugi miesiac: [120  98 167 201 156 198]


In [18]:
print(f'sprzedaz od tyłu: {miesiace_sprzedaz[::-1]}')

sprzedaz od tyłu: [221 198 143 156 178 201 189 167 142  98 135 120]


## Ćwiczenie 2
*Część B* - macierz 2D

In [20]:
dane = np.array([
    [120, 145, 167], # Produkt A
    [89, 102, 95], # Produkt B
    [234, 267, 289], # Produkt C
    [56, 78, 91], # Produkt D
])

produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [21]:
print(f'Sprzedaż Produktu A w Q2: {dane[0, 1]}')

Sprzedaż Produktu A w Q2: 145


In [22]:
print(f'Cała sprzedaż Produktu C: {dane[2]}')

Cała sprzedaż Produktu C: [234 267 289]


In [24]:
print(f'Sprzedaż wszystkich produktów w Q1: {dane[:, 0]}')

Sprzedaż wszystkich produktów w Q1: [120  89 234  56]


In [25]:
print(f'Sprzedaż Produktów B i C w Q2 i Q3: {dane[1:3, 1:3]}')

Sprzedaż Produktów B i C w Q2 i Q3: [[102  95]
 [267 289]]


## Ćwiczenie 3
Operacje wektorowe

In [3]:
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']

ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

Zadanie 1: Podstawowe statystyki cenowe

In [14]:
print (f'Średnia cena: {ceny.mean()}')
id_min = ceny.argmin()
id_max = ceny.argmax()
print (f'Najtańszy produkt: {ceny.min()} - {nazwy[id_min]}')
print (f'Najdroższy produkt {ceny.max()} - {nazwy[id_max]}')

Średnia cena: 1171.0
Najtańszy produkt: 89 - Ładowarka
Najdroższy produkt 3499 - Laptop


Zadanie 2: Wartość magazynu

In [11]:
wartosci = ceny * ilosci_magazyn
print(f'Wartość każdego produktu: {wartosci}')
print(f'Łączna wartość magazynu: {wartosci.sum()}')

Wartość każdego produktu: [ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
Łączna wartość magazynu: 549465


Zadanie 3: Analiza cenowa

In [16]:
promo = ceny * 0.85
vat = ceny * 1.23
print(f'Ceny po rabacie: {promo}')
print(f'Ceny z VAT: {vat}')
print(f'Produkty powyżej 1000 zł: {(ceny > 1000).sum()}')

Ceny po rabacie: [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny z VAT: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
Produkty powyżej 1000 zł: 4


Zadanie 4: Filtrowanie

In [ ]:
goodrate = oceny_klientow >= 4.5
nazwy = np.array(nazwy)
print('Produkty z oceną >= 4.5:')
print(nazwy[goodrate])
print(ceny[goodrate])

Produkty z oceną >= 4.5:
['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
[3499 2499  349 1499]


In [23]:
tanie = ceny < 200
print('Produkty poniżej 200 zł')
print(nazwy[tanie])
print(ilosci_magazyn[tanie])

Produkty poniżej 200 zł
['Ładowarka' 'Mysz']
[312 201]


Zadanie 5: Analiza zapasów

In [33]:
niskistan = ilosci_magazyn < 30
wartosci = ceny * ilosci_magazyn
procent = (wartosci[niskistan].sum() / wartosci.sum()) * 100
print(f'Produkty z niskim stanem magazynowym: {nazwy[niskistan]}')
print(f'Łączna wartość tych produktów: {wartosci[niskistan].sum()}')
print(f'Procent magazynu: {procent}%')


Produkty z niskim stanem magazynowym: ['Laptop' 'Monitor']
Łączna wartość tych produktów: 86962
Procent magazynu: 15.826667758637946%


Zadanie 6 (bonus): Analiza korelacji cena–ocena

In [37]:
okazja = (oceny_klientow >= 4.5) & (ceny < 1000)
wysokie = (oceny_klientow >= 4.0)
niskie = (oceny_klientow < 4.0)
print(f'Produkty które są okazją: {nazwy[okazja]} - {ceny[okazja]}')
print(f'Średnia cena produktów z oceną >= 4.0 - {ceny[wysokie].mean()}, z oceną < 4.0 - {ceny[niskie].mean()}')


Produkty które są okazją: ['Słuchawki'] - [349]
Średnia cena produktów z oceną >= 4.0 - 1446.142857142857, z oceną < 4.0 - 529.0


## Ćwiczenie 4
Benchmark - lista vs NumPy

In [38]:
import time

Test 1: mnożenie

In [39]:
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [40]:
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter()- start

In [41]:
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter()- start

In [42]:
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 97.4 ms
NumPy: 6.7 ms
NumPy jest 14× szybszy!


Test 2: suma

In [43]:
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter()- start

In [44]:
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter()- start

In [45]:
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 37.2 ms
NumPy: 2.7 ms
NumPy jest 14× szybszy!


Test 3: flitrowanie (elementy > 500000)

In [46]:
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter()- start

In [47]:
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter()- start

In [48]:
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 54.6 ms
NumPy: 5.9 ms
NumPy jest 9× szybszy!


## Wnioski z benchmarku
- NumPy jest **14x** szybszy w mnożeniu
- NumPy jest **14×** szybszy w sumowaniu
- NumPy jest **9×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list