# Laboratorium 4 — NumPy zaawansowane
**Autor: Martyna Myśliwiec** 

In [2]:
import numpy as np

## Ćwiczenie 1: Broadcasting
Zastosowania biznesowe

In [3]:
ceny = np.array([[29.99, 31.99, 28.99],
[49.99, 52.99, 47.99],
[14.99, 15.99, 13.99],
[99.99, 104.99, 94.99]]) 
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") 

Kształt macierzy: (4, 3)


In [4]:
inflacja = ceny * 1.05
print(inflacja)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


In [5]:
rabaty = np.array([0.10, 0.05, 0.15])
poRabacie = ceny * (1 - rabaty)
print(poRabacie)

[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


In [6]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
kosztZakupu = ceny / (1 + marza)
print(kosztZakupu)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


In [8]:
idmin = ceny.argmin(axis=1)
sklepy = np.array(sklepy)
print(sklepy[idmin])

['Online' 'Online' 'Online' 'Online']


## Ćwiczenie 2
Reshape i łączenie danych

In [9]:
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


In [11]:
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f'Wszystkie: \n{wszystkie}')
print(f'Suma per oddział: {wszystkie.sum(axis=1)}')
print(f'Suma per kwartał: {wszystkie.sum(axis=0)}')

Wszystkie: 
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [15]:
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
#1
sprzedaz = sprzedaz_flat.reshape(6, 2)
print(sprzedaz)
#2
print(f'Srednia sprzedaż per produkt: {sprzedaz.mean(axis=1)}')
#3
print(f'Zmiana między mieisiącem 1 a 2: {sprzedaz[:, 1] - sprzedaz[:, 0]}')

[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
Srednia sprzedaż per produkt: [150. 225. 215. 170. 240. 225.]
Zmiana między mieisiącem 1 a 2: [100 150 -70 100 140 -70]


In [ ]:
sprzedaz = sprzedaz.flatten()
print(sprzedaz)
nowyMiesiac = np.array([235])
sprzedazPlus = np.concatenate([sprzedaz, nowyMiesiac])
print(sprzedazPlus)


[100 200 150 300 250 180 120 220 170 310 260 190]
[100 200 150 300 250 180 120 220 170 310 260 190 235]


## Ćwiczenie 3
Analiza danych finansowych

In [18]:
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

In [22]:
#1
print(f'Srednia pensja: {pensje.mean()}')
print(f'Mediana pensji: {np.median(pensje)}')
print(f'Odchylenie standardowe pensji: {pensje.std()}')
#2
pracownicy = np.array(pracownicy)
bogacze = (pensje > pensje.mean())
print(f'Osoby zarabiające powyżej sredniej: {pracownicy[bogacze]}')
#3
stazysci = (pensje < np.median(pensje))
print(f'Osoby zarabiające poniżej mediany: {pracownicy[stazysci]}')
#4
rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(f'Rozstęp wynagrodzeń: {rozstep}')
print(f'Rozstęp międzykwartalny: {iqr}')

Srednia pensja: 6425.0
Mediana pensji: 6050.0
Odchylenie standardowe pensji: 1616.9029037020127
Osoby zarabiające powyżej sredniej: ['Jan' 'Marek' 'Zofia']
Osoby zarabiające poniżej mediany: ['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp wynagrodzeń: 4900
Rozstęp międzykwartalny: 2200.0


In [26]:
premia = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4, 1000, 0))
noweWynagrodzenie = pensje + premia
print(noweWynagrodzenie)
idmax = premia.argmax()
print(pracownicy[idmax])

[ 6500  7200  6800 10100  8300  4200  9500  5800]
Ewa


In [32]:
kolejnosc = np.argsort(pensje)[::-1]
for i, idx in enumerate(kolejnosc, 1):
    print(i, pracownicy[idx], pensje[idx], staz[idx])
    i += 1

1 Marek 9100 15
2 Zofia 8500 12
3 Jan 7200 8
4 Kasia 6300 5
5 Tomek 5800 4
6 Anna 5500 3
7 Ewa 4800 2
8 Piotr 4200 1


In [30]:
korelacjaSP = np.corrcoef(staz, pensje)[0, 1]
korelacjaSO = np.corrcoef(staz, oceny)[0, 1]
print(f'Korelacja: staż vs pensja: {korelacjaSP}')
print(f'Korelacja: staż vs ocena: {korelacjaSO}')
print(f'Silniejszy związek jest między stażem a pensją')

Korelacja: staż vs pensja: 0.987862864584301
Korelacja: staż vs ocena: 0.04198471605953068
Silniejszy związek jest między stażem a pensją


In [46]:
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol
print(przychod)
przychodMax = przychod.sum(axis = 1).argmax()
najlepszyMiesiąc = przychod.sum(axis = 0).argmax()
początek = przychod[:, :3].sum()
koniec = przychod[:, 3:].sum()
print(f'Największy łączny przychód przyniósł produkt: {produkty_nazwy[przychodMax]}')
print(f'Najlepszy miesiąc pod kątem sprzedaży to: {najlepszyMiesiąc + 1}')
print(f'Suma pierwsze 3 m-ce: {początek}, suma ostatnie 3 m-ce: {koniec}')

[[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]
Największy łączny przychód przyniósł produkt: Smartfon
Najlepszy miesiąc pod kątem sprzedaży to: 2
Suma pierwsze 3 m-ce: 2463950, suma ostatnie 3 m-ce: 2536500


## Ćwiczenie 4
Generowanie danych 

In [47]:
np.random.seed(42)

In [48]:
wiek = np.random.normal(loc = 35, scale = 10, size = 100)
wiek = np.clip(wiek, 18, None).astype(int)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)


In [52]:
print(f'Wiek - srednia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, odchylenie standardowe: {wiek.std():.1f}, minimum: {wiek.min()}, maksimum: {wiek.max()}')
print(f'Wydatki - srednia: {wydatki.mean():.1f}, mediana: {np.median(wydatki):.1f}, odchylenie standardowe: {wydatki.std():.1f}, minimum: {wydatki.min():.1f}, maksimum: {wydatki.max():.1f}')
print(f'Wizyty - srednia: {wizyty.mean():.1f}, mediana: {np.median(wizyty):.1f}, odchylenie standardowe: {wizyty.std():.1f}, minimum: {wizyty.min()}, maksimum: {wizyty.max()}')

Wiek - srednia: 33.6, mediana: 33.0, odchylenie standardowe: 8.6, minimum: 18, maksimum: 53
Wydatki - srednia: 504.5, mediana: 516.8, odchylenie standardowe: 189.8, minimum: 116.2, maksimum: 1044.0
Wizyty - srednia: 4.9, mediana: 5.0, odchylenie standardowe: 2.2, minimum: 1, maksimum: 11


In [58]:
print(f'Korelacja: wiek vs wydatki: {np.corrcoef(wiek, wydatki)[0, 1]:.2f}')
print(f'Korelacja: wizyty vs wydatki: {np.corrcoef(wizyty, wydatki)[0, 1]:.2f}')
segmentacja = np.where(wydatki > wydatki.mean() + wydatki.std(), 'WYSOKI', np.where(wydatki < wydatki.mean() - wydatki.std(), 'NISKI', 'SREDNI'))
print(segmentacja)



Korelacja: wiek vs wydatki: -0.12
Korelacja: wizyty vs wydatki: -0.16
['NISKI' 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI' 'WYSOKI' 'SREDNI'
 'SREDNI' 'SREDNI' 'NISKI' 'SREDNI' 'SREDNI' 'WYSOKI' 'SREDNI' 'SREDNI'
 'SREDNI' 'NISKI' 'WYSOKI' 'SREDNI' 'SREDNI' 'SREDNI' 'WYSOKI' 'NISKI'
 'SREDNI' 'WYSOKI' 'NISKI' 'SREDNI' 'SREDNI' 'SREDNI' 'NISKI' 'SREDNI'
 'NISKI' 'SREDNI' 'SREDNI' 'WYSOKI' 'SREDNI' 'SREDNI' 'SREDNI' 'NISKI'
 'SREDNI' 'WYSOKI' 'NISKI' 'SREDNI' 'SREDNI' 'SREDNI' 'NISKI' 'NISKI'
 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI'
 'WYSOKI' 'SREDNI' 'NISKI' 'SREDNI' 'NISKI' 'SREDNI' 'WYSOKI' 'SREDNI'
 'SREDNI' 'SREDNI' 'SREDNI' 'WYSOKI' 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI'
 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI' 'WYSOKI' 'SREDNI' 'WYSOKI'
 'SREDNI' 'SREDNI' 'NISKI' 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI' 'SREDNI'
 'SREDNI' 'NISKI' 'SREDNI' 'SREDNI' 'SREDNI' 'NISKI' 'SREDNI' 'SREDNI'
 'SREDNI' 'SREDNI' 'SREDNI' 'NISKI']


In [59]:
nazwy_seg, liczniki = np.unique(segmentacja, return_counts=True)
for nazwa, ile in zip(nazwy_seg, liczniki):
    print(f'Segment {nazwa}: {ile} klientow')

Segment NISKI: 17 klientow
Segment SREDNI: 71 klientow
Segment WYSOKI: 12 klientow
